version: '3.8'
services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5m
      timeout: 10s
      retries: 3

  simulation:
    build: .
    command: python run_simulation.py
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 5m
      timeout: 10s
      retries: 3

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5m
      timeout: 10s
      retries: 3 