version: '3.8'
services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@8.219.101.54:15432/mydatabase
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health" ]
      interval: 5m
      timeout: 10s
      retries: 3

  simulation:
    build: .
    command: python run_simulation.py
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@8.219.101.54:15432/mydatabase
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 5m
      timeout: 10s
      retries: 3 